baseURL = 'https://charivnk.github.io/'
languageCode = 'uk'
theme = 'blowfish'
defaultContentLanguageInSubdir = false
disableDefaultLanguageRedirect = false
disableLanguages = ['en']
[caches]
  [caches.images]
    dir = ':cacheDir/images'
[params]
  title = 'Мій власний блог'
  description = 'Блог про малювання, 3d моделювання, blender3d, 3dcoat'
  defaultContentLanguage = 'uk'
  author = 'charivnk'
  enableRobotsTXT = true
[permalinks]
  posts = "/:year/:month/:day/:slug/"
  categories = "/categories/:slug/"
  tags = "/tags/:slug/"
[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"
[server]
  [[server.headers]]
    for = "/*"
    [server.headers.values]
      Strict-Transport-Security = "max-age=31536000; includeSubDomains"
      X-Content-Type-Options = "nosniff"
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"
